### ISSUE TITLE
Not passing searchParams for findRemote may cause exception

### ISSUE THREAD

**Issue by SparK-Cruz** [raphaelpereira/Backbone.RailsStore#8]
The findRemote method doesn't have default options (empty object for searchParams).
So when you check for `params[:key]` at self.rails_store_search, ruby complains about not being able to convert symbol `:key` to integer (as if params was an array). Forcing you to pass a `searchParams: {}` to findRemote options, which should be the default value.

**Comment by raphaelpereira** [comment]
Do you mean [here](https://github.com/raphaelpereira/Backbone.RailsStore/blob/master/app/controllers/backbone_rails_store_controller.rb#L154) ?

Does this solve?

``` ruby
result = rails_class.rails_store_search(model_info[:searchParams] || {})
```

**Comment by raphaelpereira** [comment]
@SparK-Cruz ping

**Comment by SparK-Cruz** [comment]
I guess so
